export type Language = "en" | "zh";

const papers = [
  {
    title: "Detecting Semantic Manipulation in Structured Academic Figures: A Benchmark and a Structured-Extraction Baseline",
    shortTitle: "Semantic Manipulation in Academic Figures",
    status: "Project outcome",
    statusZh: "项目成果",
    year: "2026",
    authors: "Fengkai Gao",
    description: {
      en: "Introduces SciFigSem-1K, a 1,000-sample benchmark for detecting contradictions between visual evidence and textual or numeric claims in structured academic figures, together with an auditable structured-extraction baseline.",
      zh: "提出 SciFigSem-1K：一个包含 1,000 个样本的结构化学术图表语义篡改基准，并设计可审计的结构化抽取基线，用于识别视觉证据与文字或数值声明之间的矛盾。",
    },
    contribution: {
      en: "Benchmark design · VLM evaluation · Structured visual reasoning",
      zh: "基准设计 · 视觉语言模型评估 · 结构化视觉推理",
    },
    tags: ["Scientific figures", "VLM evaluation", "Visual integrity"],
    figureAlt: {
      en: "Pipeline for detecting semantic manipulation in structured academic figures",
      zh: "结构化学术图表语义篡改检测流程图",
    },
    cover: "/images/papers/semantic-figure-pipeline.png",
    pdf: "/papers/semantic-figure-manipulation.pdf",
    code: "https://github.com/QCYTSN/DSMAF_Light",
  },
  {
    title: "Training-Free Concept Disentanglement in Text-to-Image Generation via Detection-Guided Attention Control",
    shortTitle: "Detection-Guided Attention Control",
    status: "Project outcome",
    statusZh: "项目成果",
    year: "2026",
    authors: "Fengkai Gao",
    description: {
      en: "Proposes a training-free spatial-gated attention framework that uses open-vocabulary detection priors to reduce attribute leakage in text-to-image diffusion while preserving natural image composition.",
      zh: "提出无需训练的空间门控注意力框架，利用开放词汇检测器提供布局先验，在保持自然构图的同时减少文本生成图像中的属性泄漏。",
    },
    contribution: {
      en: "Training-free control · Cross-attention · Concept disentanglement",
      zh: "免训练控制 · 交叉注意力 · 概念解耦",
    },
    tags: ["Text-to-image", "Diffusion", "Attention control"],
    figureAlt: {
      en: "Detection-guided attention control method pipeline for text-to-image generation",
      zh: "文本生成图像的检测引导注意力控制方法流程图",
    },
    cover: "/images/papers/detection-guided-pipeline.png",
    pdf: "/papers/detection-guided-attention.pdf",
    code: "https://github.com/QCYTSN/Training-Free-Concept-Disentanglement-in-T2I-Generation-via-Detection-Guided-Attention-Control",
  },
  {
    title: "Revisiting FreeU: Frequency-Domain Analysis and Dynamic Feature Modulation for Diffusion Models",
    shortTitle: "Dynamic FreeU",
    status: "Project outcome",
    statusZh: "项目成果",
    year: "2025",
    authors: "Fengkai Gao · Jiatong Zhu",
    description: {
      en: "Reproduces FreeU with precise feature intervention, validates its behavior through latent Fourier analysis, and proposes a time-aware Dynamic FreeU schedule that balances structural guidance with texture preservation.",
      zh: "通过精确的特征干预复现 FreeU，并以潜空间傅里叶分析验证其作用机制；进一步提出随时间变化的 Dynamic FreeU，在结构引导和纹理保留之间取得平衡。",
    },
    contribution: {
      en: "Frequency analysis · U-Net features · Dynamic modulation",
      zh: "频域分析 · U-Net 特征 · 动态调制",
    },
    tags: ["Diffusion", "FreeU", "Frequency domain"],
    figureAlt: {
      en: "Dynamic FreeU method pipeline with frequency analysis and feature modulation",
      zh: "结合频域分析与特征调制的 Dynamic FreeU 方法流程图",
    },
    cover: "/images/papers/dynamic-freeu-pipeline.png",
    pdf: "/papers/dynamic-freeu.pdf",
    code: null,
  },
] as const;

const shared = {
  name: "Fengkai Gao",
  papers,
  contact: {
    email: "t330034007@mail.bnbu.edu.cn",
    github: "https://github.com/QCYTSN",
    githubLabel: "github.com/QCYTSN",
  },
} as const;

export const portfolioContent = {
  en: {
    ...shared,
    locale: "en",
    languageName: "English",
    languageAction: "中文",
    menu: "Menu",
    navigationLabel: "Primary navigation",
    navigation: [
      { label: "Home", href: "#home" },
      { label: "Projects", href: "#projects" },
      { label: "Research", href: "#research" },
      { label: "Profile", href: "#profile" },
    ],
    contactAction: "Contact",
    eyebrow: "Researcher · Computer Vision · Vision-Language Models · Generative Models",
    headline: "How machines see—and how we can make their vision more reliable.",
    headlineLines: ["How machines see—", "and how we can make", "their vision more reliable."],
    description: "My research moves between understanding visual evidence and controlling generative models, with an emphasis on interpretable experiments and practical systems.",
    primaryAction: "Explore selected work",
    secondaryAction: "Research profile",
    projectSignal: "selected projects · 2025–2026",
    archiveHint: "DRAG TO COMPARE / CLICK TO LOCK",
    scrollLabel: "Scroll to explore",
    workKicker: "01 / Selected projects",
    workTitle: "Projects, made visible.",
    workIntro: "Three project outcomes across scientific figure integrity, controllable generation, and diffusion-model analysis.",
    figureLabel: "Project report",
    readPaper: "View project report",
    viewCode: "View code",
    researchKicker: "02 / Research directions",
    researchTitle: "From visual evidence to controlled generation.",
    researchBack: "Research index",
    researchExplore: "Explore field",
    conceptDemoLabel: "Interactive conceptual demo",
    demoGuideLabel: "How to read this demo",
    demoGuideHeadings: ["What to observe", "Try this", "Why it happens"],
    interests: [
      {
        slug: "visual-reasoning",
        title: "Computer Vision & Visual Reasoning",
        heroLabel: "Visual evidence → structured reasoning",
        description: "Recovering structure, relationships, and semantic consistency from complex visual evidence.",
        detailIntro: "Vision becomes useful when a system can move beyond isolated objects and recover the evidence, structure, and relationships inside a scene.",
        detailNote: "Move the scanner across the scene, then select an entity to expose its local evidence graph.",
        keywords: ["Scene structure", "Evidence graphs", "Spatial relations"],
        guide: [
          "Watch the blue scan boundary turn a flat chart into detected regions, entities, and explicit relationships.",
          "Move across the chart to reveal more structured evidence, then select Plot, Trend, or Caption to change the active relation.",
          "Visual reasoning systems become easier to audit when they convert pixels into intermediate objects and links instead of jumping directly to an answer.",
        ],
      },
      {
        slug: "vlm-evaluation",
        title: "Vision-Language Model Evaluation",
        heroLabel: "Controlled corruption → model failure",
        description: "Designing controlled benchmarks that reveal how multimodal models reason—and where they fail.",
        detailIntro: "A fluent answer is not always a reliable one. Controlled visual perturbations help reveal when multimodal understanding begins to break.",
        detailNote: "Apply visual corruption and watch the answer, confidence, and failure diagnosis change together.",
        keywords: ["Robustness", "Failure analysis", "Controlled evaluation"],
        guide: [
          "Watch confidence fall as the chart loses visual evidence; beyond a mode-specific threshold, the answer and diagnosis switch to failure.",
          "Choose blur, compression, or occlusion, then raise the corruption slider and compare how quickly each perturbation breaks grounding.",
          "Different corruptions remove different cues. Once bars, labels, or their spatial correspondence become unreliable, a model can remain fluent while selecting the wrong evidence.",
        ],
      },
      {
        slug: "generative-models",
        title: "Controllable Generative Models",
        heroLabel: "Attention → controllable generation",
        description: "Studying attention, feature modulation, and inference-time control in text-to-image diffusion.",
        detailIntro: "Controllable generation asks how semantic intent, spatial layout, structure, and texture can be adjusted without losing visual coherence.",
        detailNote: "Tune the denoising trajectory, structural guidance, and texture energy inside a compact latent control console.",
        keywords: ["Latent control", "Attention", "Diffusion dynamics"],
        guide: [
          "Watch residual noise, spatial adherence, and high-frequency texture respond independently while the selected prompt token changes the controlled attribute.",
          "Switch between the hat, scarf, and light tokens; then vary denoising, structure guidance, and texture energy one control at a time.",
          "Diffusion inference gradually removes noise, while attention and feature modulation bias where semantic attributes appear and how strongly structure or texture is preserved.",
        ],
      },
    ],
    profileKicker: "03 / Profile",
    profileTitle: "Research grounded in how models actually behave.",
    about: "I am an Artificial Intelligence undergraduate at Beijing Normal-Hong Kong Baptist University (BNBU). I research computer vision, multimodal reasoning, and generative models, and I enjoy turning model behavior into experiments that can be inspected and explained.",
    profileLabels: {
      email: "Email",
      school: "School",
      major: "Major",
      coursework: "Selected coursework",
      directions: "Research directions",
      github: "GitHub",
    },
    school: "Beijing Normal-Hong Kong Baptist University (BNBU)",
    major: "BSc Artificial Intelligence",
    coursework: ["Machine Learning", "Computer Vision", "Natural Language Processing", "Bayesian Networks", "Big Data"],
    directionNames: ["Computer Vision", "Multimodal Reasoning", "Generative Models"],
    backToTop: "Back to top",
    loaderLabel: "Preparing research portfolio",
  },
  zh: {
    ...shared,
    locale: "zh",
    languageName: "中文",
    languageAction: "EN",
    menu: "菜单",
    navigationLabel: "主导航",
    navigation: [
      { label: "主页", href: "#home" },
      { label: "项目", href: "#projects" },
      { label: "研究", href: "#research" },
      { label: "个人信息", href: "#profile" },
    ],
    contactAction: "联系我",
    eyebrow: "研究者 · 计算机视觉 · 视觉语言模型 · 生成模型",
    headline: "机器如何看见，以及如何让这种视觉更加可靠。",
    headlineLines: ["机器如何看见，", "以及如何让这种视觉", "更加可靠。"],
    description: "我的研究连接视觉证据理解与生成模型控制，重视可解释的实验设计，也关注方法如何真正落地。",
    primaryAction: "查看精选研究",
    secondaryAction: "了解研究方向",
    projectSignal: "个精选项目 · 2025–2026",
    archiveHint: "拖动对照 / 点击锁定",
    scrollLabel: "向下探索",
    workKicker: "01 / 精选项目",
    workTitle: "让项目成果，被清晰地看见。",
    workIntro: "三个项目成果，涵盖学术图表完整性、可控图像生成与扩散模型机理分析。",
    figureLabel: "项目报告",
    readPaper: "查看项目报告",
    viewCode: "查看代码",
    researchKicker: "02 / 研究方向",
    researchTitle: "从理解视觉证据，到控制生成过程。",
    researchBack: "返回研究目录",
    researchExplore: "进入方向",
    conceptDemoLabel: "交互式概念演示",
    demoGuideLabel: "如何理解这个演示",
    demoGuideHeadings: ["观察什么", "如何操作", "为什么会这样"],
    interests: [
      {
        slug: "visual-reasoning",
        title: "计算机视觉与视觉推理",
        heroLabel: "视觉证据 → 结构化推理",
        description: "从复杂视觉证据中恢复结构、关系与语义一致性。",
        detailIntro: "视觉系统只有从单个目标进一步恢复场景中的证据、结构和关系，才真正具备可用的理解能力。",
        detailNote: "移动扫描镜观察场景，再选择实体以展开对应的局部证据图谱。",
        keywords: ["场景结构", "证据图谱", "空间关系"],
        guide: [
          "观察蓝色扫描边界如何将一张平面图表转化为被识别的区域、实体与显式关系。",
          "在图表上移动指针以逐步显露结构化证据，再选择图形、趋势或图注，切换当前查看的证据关系。",
          "视觉推理系统如果先把像素转换为中间对象与关系，再形成答案，其推理过程就更容易被检查和解释。",
        ],
      },
      {
        slug: "vlm-evaluation",
        title: "视觉语言模型评估",
        heroLabel: "可控扰动 → 模型失效",
        description: "设计可控基准，分析多模态模型如何推理，以及它们在何处失效。",
        detailIntro: "流畅的回答并不一定可靠。通过可控视觉扰动，可以观察多模态理解在什么条件下开始失效。",
        detailNote: "施加视觉扰动，观察答案、置信度和错误诊断如何同时变化。",
        keywords: ["鲁棒性", "错误分析", "可控评估"],
        guide: [
          "观察图表证据受损时置信度如何下降；超过不同扰动对应的阈值后，回答与诊断会切换为失败状态。",
          "选择模糊、压缩或遮挡，再提高扰动强度，比较哪类视觉破坏会更早导致定位失败。",
          "不同扰动会移除不同线索。当柱形、文字或二者的空间对应变得不可靠时，模型仍可能流畅作答，却引用了错误证据。",
        ],
      },
      {
        slug: "generative-models",
        title: "可控生成模型",
        heroLabel: "注意力 → 可控生成",
        description: "研究文本生成图像扩散模型中的注意力、特征调制与推理时控制。",
        detailIntro: "可控生成关注如何调节语义意图、空间布局、结构与纹理，同时保持最终图像的视觉一致性。",
        detailNote: "在潜空间控制台中调节去噪过程、结构引导和纹理能量。",
        keywords: ["潜空间控制", "注意力", "扩散动力学"],
        guide: [
          "观察残余噪声、空间约束和高频纹理如何分别变化，同时提示词 Token 会改变被控制的视觉属性。",
          "在帽子、围巾和光照 Token 之间切换，再分别调节去噪、结构引导和纹理能量，比较单个控制量的影响。",
          "扩散推理会逐步去除噪声，而注意力与特征调制决定语义属性出现的位置，以及结构和纹理被保留的强度。",
        ],
      },
    ],
    profileKicker: "03 / 个人信息",
    profileTitle: "从模型的真实行为出发，做可以被验证的研究。",
    about: "我就读于北京师范大学-香港浸会大学联合国际学院（BNBU）人工智能专业，研究兴趣集中在计算机视觉、多模态推理与生成模型。我喜欢把模型行为转化为能够被观察、检验和解释的实验。",
    profileLabels: {
      email: "邮箱",
      school: "学校",
      major: "专业",
      coursework: "主修课程",
      directions: "研究方向",
      github: "GitHub",
    },
    school: "北京师范大学-香港浸会大学联合国际学院（BNBU）",
    major: "人工智能 理学学士",
    coursework: ["机器学习", "计算机视觉", "自然语言处理", "贝叶斯网络", "大数据"],
    directionNames: ["计算机视觉", "多模态推理", "生成模型"],
    backToTop: "返回顶部",
    loaderLabel: "正在准备研究主页",
  },
} as const;
